// <auto-generated />
using BeastBoards.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeastBoards.Api.Migrations
{
    [DbContext(typeof(BeastBoardsContext))]
    [Migration("20251226163905_Leaderboard")]
    partial class Leaderboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BeastBoards.Api.Models.LeaderboardTiming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<ulong>("SteamId")
                        .HasColumnType("bigint unsigned");

                    b.Property<float>("Time")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BeastBoards_LeaderboardTimings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
